# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_files/mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(651, 416)
        HomeWindow.setMinimumSize(QtCore.QSize(0, 416))
        HomeWindow.setMaximumSize(QtCore.QSize(16777215, 416))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        HomeWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.select_vault_screen = QtWidgets.QWidget()
        self.select_vault_screen.setObjectName("select_vault_screen")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.select_vault_screen)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.select_vault_screen)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.select_vault_screen)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.vaults_list = QtWidgets.QListWidget(self.select_vault_screen)
        self.vaults_list.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        self.vaults_list.setFont(font)
        self.vaults_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vaults_list.setStyleSheet("QListWidget {\n"
"        background-color: transparent;\n"
"    }\n"
"\n"
"    QListWidget::Item {\n"
"        background-color: #3498db; /* Set your desired background color */\n"
"        color: white; /* Set text color */\n"
"        width: 50%;\n"
"        height: 50%;\n"
"        border-radius: 35%; /* Make it circular */\n"
"        padding: 10px; /* Adjust padding as needed */\n"
"        margin: 11px; /* Adjust margins as needed */\n"
"    }\n"
"\n"
"    QListWidget::Item:selected {\n"
"        background-color: #2980b9; /* Set the selected item color */\n"
"    }")
        self.vaults_list.setFlow(QtWidgets.QListView.LeftToRight)
        self.vaults_list.setObjectName("vaults_list")
        self.verticalLayout_4.addWidget(self.vaults_list)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.select_vault_screen)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.login_edit = QtWidgets.QLineEdit(self.groupBox)
        self.login_edit.setMinimumSize(QtCore.QSize(200, 26))
        self.login_edit.setStyleSheet("QLineEdit{\n"
"min-height: 25%;\n"
"border-bottom: 1px solid grey;\n"
"border-left: 1px solid grey;\n"
"border-top: none;\n"
"border-right: none;\n"
"}")
        self.login_edit.setObjectName("login_edit")
        self.horizontalLayout_5.addWidget(self.login_edit)
        self.horizontalLayout_6.addWidget(self.groupBox, 0, QtCore.Qt.AlignRight)
        self.login_button = QtWidgets.QPushButton(self.select_vault_screen)
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setStyleSheet("QPushButton{\n"
"width: 30px;\n"
"height: 30px;\n"
"border-radius: 12px;\n"
"background-color: rgb(255, 254, 254);\n"
"color: rgb(69, 25, 255);\n"
"}")
        self.login_button.setObjectName("login_button")
        self.horizontalLayout_6.addWidget(self.login_button, 0, QtCore.Qt.AlignLeft)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.add_vault_bttn = QtWidgets.QPushButton(self.select_vault_screen)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        self.add_vault_bttn.setFont(font)
        self.add_vault_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_vault_bttn.setStyleSheet("QPushButton{\n"
"width: 50px;\n"
"height: 50px;\n"
"border-radius: 25px;\n"
"background-color: rgb(255, 254, 254);\n"
"color: rgb(69, 25, 255);\n"
"}")
        self.add_vault_bttn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/ui_files/../images/add_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_vault_bttn.setIcon(icon)
        self.add_vault_bttn.setIconSize(QtCore.QSize(40, 40))
        self.add_vault_bttn.setObjectName("add_vault_bttn")
        self.horizontalLayout_6.addWidget(self.add_vault_bttn)
        self.delete_vault_bttn = QtWidgets.QPushButton(self.select_vault_screen)
        self.delete_vault_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_vault_bttn.setStyleSheet("QPushButton{\n"
"width: 50px;\n"
"height: 50px;\n"
"border-radius: 25px;\n"
"background-color: rgb(255, 254, 254);\n"
"color: rgb(69, 25, 255);\n"
"}")
        self.delete_vault_bttn.setObjectName("delete_vault_bttn")
        self.horizontalLayout_6.addWidget(self.delete_vault_bttn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.select_vault_screen)
        self.new_vault_screen = QtWidgets.QWidget()
        self.new_vault_screen.setObjectName("new_vault_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.new_vault_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.label_6 = QtWidgets.QLabel(self.new_vault_screen)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.new_vault_screen)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.new_name_edit = QtWidgets.QLineEdit(self.new_vault_screen)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.new_name_edit.setFont(font)
        self.new_name_edit.setStyleSheet("QLineEdit{\n"
"min-height: 35%;\n"
"border-bottom: 1px solid grey;\n"
"border-left: 1px solid grey;\n"
"border-top: none;\n"
"border-right: none;\n"
"}")
        self.new_name_edit.setText("")
        self.new_name_edit.setObjectName("new_name_edit")
        self.verticalLayout.addWidget(self.new_name_edit)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.label_8 = QtWidgets.QLabel(self.new_vault_screen)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.new_email_edit = QtWidgets.QLineEdit(self.new_vault_screen)
        self.new_email_edit.setStyleSheet("QLineEdit{\n"
"min-height: 35%;\n"
"border-bottom: 1px solid grey;\n"
"border-left: 1px solid grey;\n"
"border-top: none;\n"
"border-right: none;\n"
"}")
        self.new_email_edit.setObjectName("new_email_edit")
        self.verticalLayout.addWidget(self.new_email_edit)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.label_9 = QtWidgets.QLabel(self.new_vault_screen)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.new_pw_edit = QtWidgets.QLineEdit(self.new_vault_screen)
        self.new_pw_edit.setStyleSheet("QLineEdit{\n"
"min-height: 35%;\n"
"border-bottom: 1px solid grey;\n"
"border-left: 1px solid grey;\n"
"border-top: none;\n"
"border-right: none;\n"
"}")
        self.new_pw_edit.setObjectName("new_pw_edit")
        self.verticalLayout.addWidget(self.new_pw_edit)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.back_button = QtWidgets.QPushButton(self.new_vault_screen)
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_7.addWidget(self.back_button, 0, QtCore.Qt.AlignLeft)
        self.create_button = QtWidgets.QPushButton(self.new_vault_screen)
        self.create_button.setObjectName("create_button")
        self.horizontalLayout_7.addWidget(self.create_button, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.stackedWidget.addWidget(self.new_vault_screen)
        self.main_screen = QtWidgets.QWidget()
        self.main_screen.setObjectName("main_screen")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.main_screen)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.main_screen)
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"        alignment: center;\n"
"    }\n"
"\n"
"    QTabBar::tab {\n"
"        background-color: #3498db; /* Tab background color */\n"
"        color: #FFFFFF; /* Tab text color */\n"
"        padding: 8px 16px; /* Tab padding */\n"
"        border: 1px solid #2980b9; /* Tab border */\n"
"        border-top-left-radius: 4px;\n"
"        border-top-right-radius: 4px;\n"
"    }\n"
"\n"
"    QTabBar::tab:selected {\n"
"        background-color: #2980b9; /* Selected tab background color */\n"
"        color: #FFFFFF; /* Selected tab text color */\n"
"    }\n"
"\n"
"    QTabBar::tab:hover {\n"
"        background-color: #4aa3df; /* Hovered tab background color */\n"
"    }")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.addTab = QtWidgets.QWidget()
        self.addTab.setObjectName("addTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.addTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.email_eddit = QtWidgets.QLineEdit(self.addTab)
        self.email_eddit.setStyleSheet("QLineEdit{\n"
"height: 25px;\n"
"border-top: none;\n"
"border-bottom: 1px solid grey;\n"
"border-left: 1px solid grey;\n"
"}\n"
"")
        self.email_eddit.setObjectName("email_eddit")
        self.gridLayout_2.addWidget(self.email_eddit, 1, 0, 1, 1)
        self.account_name_edit = QtWidgets.QLineEdit(self.addTab)
        self.account_name_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.account_name_edit.setStyleSheet("QLineEdit{\n"
"height: 25px;\n"
"border-top: none;\n"
"border-bottom: 1px solid grey;\n"
"border-left: 1px solid grey;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;\n"
"}\n"
"")
        self.account_name_edit.setObjectName("account_name_edit")
        self.gridLayout_2.addWidget(self.account_name_edit, 0, 0, 1, 1)
        self.acct_pw_edit = QtWidgets.QLineEdit(self.addTab)
        self.acct_pw_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.acct_pw_edit.setStyleSheet("QLineEdit{\n"
"height: 25px;\n"
"border-top: none;\n"
"border-bottom: 1px solid grey;\n"
"border-left: 1px solid grey;\n"
"margin-top: 19px;\n"
"\n"
"}\n"
"")
        self.acct_pw_edit.setObjectName("acct_pw_edit")
        self.gridLayout_2.addWidget(self.acct_pw_edit, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.back_to_select_bttn = QtWidgets.QPushButton(self.addTab)
        self.back_to_select_bttn.setStyleSheet("QPushButton{\n"
"width: 50px;\n"
"height: 50px;\n"
"border-radius: 25px;\n"
"background-color: rgb(255, 254, 254);\n"
"color: rgb(69, 25, 255);\n"
"}")
        self.back_to_select_bttn.setObjectName("back_to_select_bttn")
        self.horizontalLayout_8.addWidget(self.back_to_select_bttn)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.add_acct_bttn = QtWidgets.QPushButton(self.addTab)
        self.add_acct_bttn.setMinimumSize(QtCore.QSize(0, 0))
        self.add_acct_bttn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add_acct_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_acct_bttn.setStyleSheet("QPushButton{\n"
"width: 50px;\n"
"height: 50px;\n"
"border-radius: 25px;\n"
"background-color: rgb(255, 254, 254);\n"
"color: rgb(69, 25, 255);\n"
"}")
        self.add_acct_bttn.setObjectName("add_acct_bttn")
        self.horizontalLayout_8.addWidget(self.add_acct_bttn)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        self.groupBox1 = QtWidgets.QGroupBox(self.addTab)
        self.groupBox1.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBox1.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(True)
        self.groupBox1.setFont(font)
        self.groupBox1.setStyleSheet("QGroupBox{\n"
"background-color: transparent;\n"
"}")
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft)
        self.pw_length_edit = QtWidgets.QSpinBox(self.groupBox1)
        self.pw_length_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pw_length_edit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhPreferNumbers)
        self.pw_length_edit.setMinimum(5)
        self.pw_length_edit.setProperty("value", 10)
        self.pw_length_edit.setObjectName("pw_length_edit")
        self.horizontalLayout_3.addWidget(self.pw_length_edit, 0, QtCore.Qt.AlignLeft)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.gridLayout_7.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.generate_pw_bttn = QtWidgets.QPushButton(self.groupBox1)
        self.generate_pw_bttn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.generate_pw_bttn.setStyleSheet("QPushButton{\n"
"width: 500px;\n"
"height: 50px;\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 254, 254);\n"
"color: rgb(69, 25, 255);\n"
"}")
        self.generate_pw_bttn.setObjectName("generate_pw_bttn")
        self.gridLayout_7.addWidget(self.generate_pw_bttn, 0, 6, 1, 1)
        self.options_group_box = QtWidgets.QGroupBox(self.groupBox1)
        self.options_group_box.setObjectName("options_group_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.options_group_box)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.numbers_chkbox = QtWidgets.QCheckBox(self.options_group_box)
        self.numbers_chkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numbers_chkbox.setObjectName("numbers_chkbox")
        self.horizontalLayout_2.addWidget(self.numbers_chkbox, 0, QtCore.Qt.AlignLeft)
        self.special_char_chkbox = QtWidgets.QCheckBox(self.options_group_box)
        self.special_char_chkbox.setObjectName("special_char_chkbox")
        self.horizontalLayout_2.addWidget(self.special_char_chkbox)
        self.uppercase_chkbox = QtWidgets.QCheckBox(self.options_group_box)
        self.uppercase_chkbox.setObjectName("uppercase_chkbox")
        self.horizontalLayout_2.addWidget(self.uppercase_chkbox)
        self.gridLayout_7.addWidget(self.options_group_box, 0, 4, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox1, 2, 0, 1, 1)
        self.tabWidget.addTab(self.addTab, "")
        self.viewTab = QtWidgets.QWidget()
        self.viewTab.setObjectName("viewTab")
        self.gridLayout = QtWidgets.QGridLayout(self.viewTab)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.viewTab)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.current_acct_label = QtWidgets.QLabel(self.groupBox_2)
        self.current_acct_label.setObjectName("current_acct_label")
        self.verticalLayout_2.addWidget(self.current_acct_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.show_email_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.show_email_edit.setEnabled(False)
        self.show_email_edit.setObjectName("show_email_edit")
        self.horizontalLayout_9.addWidget(self.show_email_edit)
        self.copy_email_bttn = QtWidgets.QPushButton(self.groupBox_2)
        self.copy_email_bttn.setStyleSheet("QPushButton{\n"
"width: 35px;\n"
"height: 35px;\n"
"border-radius: 8px;\n"
"background-color: rgb(255, 254, 254);\n"
"color: rgb(69, 25, 255);\n"
"}")
        self.copy_email_bttn.setObjectName("copy_email_bttn")
        self.horizontalLayout_9.addWidget(self.copy_email_bttn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.show_pw_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.show_pw_edit.setEnabled(False)
        self.show_pw_edit.setObjectName("show_pw_edit")
        self.horizontalLayout_10.addWidget(self.show_pw_edit)
        self.copy_pw_bttn = QtWidgets.QPushButton(self.groupBox_2)
        self.copy_pw_bttn.setStyleSheet("QPushButton{\n"
"width: 35px;\n"
"height: 35px;\n"
"border-radius: 8px;\n"
"background-color: rgb(255, 254, 254);\n"
"color: rgb(69, 25, 255);\n"
"}")
        self.copy_pw_bttn.setObjectName("copy_pw_bttn")
        self.horizontalLayout_10.addWidget(self.copy_pw_bttn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.delete_acct_bttn = QtWidgets.QPushButton(self.groupBox_2)
        self.delete_acct_bttn.setStyleSheet("QPushButton{\n"
"width: 50px;\n"
"height: 50px;\n"
"border-radius: 25px;\n"
"background-color: rgb(255, 254, 254);\n"
"color: rgb(69, 25, 255);\n"
"}")
        self.delete_acct_bttn.setObjectName("delete_acct_bttn")
        self.horizontalLayout_4.addWidget(self.delete_acct_bttn)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.edit_acct_bttn = QtWidgets.QPushButton(self.groupBox_2)
        self.edit_acct_bttn.setStyleSheet("QPushButton{\n"
"width: 50px;\n"
"height: 50px;\n"
"border-radius: 25px;\n"
"background-color: rgb(255, 254, 254);\n"
"color: rgb(69, 25, 255);\n"
"}")
        self.edit_acct_bttn.setObjectName("edit_acct_bttn")
        self.horizontalLayout_4.addWidget(self.edit_acct_bttn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addWidget(self.groupBox_2, 0, 2, 2, 1)
        self.accounts_table = QtWidgets.QListWidget(self.viewTab)
        self.accounts_table.setMinimumSize(QtCore.QSize(0, 250))
        self.accounts_table.setMaximumSize(QtCore.QSize(200, 16777215))
        self.accounts_table.setAutoFillBackground(False)
        self.accounts_table.setStyleSheet("QListWidget {\n"
"        background-color: #303030; /* Dark background color */\n"
"        color: #FFFFFF; /* Text color */\n"
"        border: 1px solid #505050; /* Border color */\n"
"        outline: none;\n"
"    }\n"
"    \n"
"    QListWidget::item {\n"
"        background-color: #404040; /* Item background color */\n"
"        border: 1px solid #505050; /* Item border color */\n"
"        padding: 10px;\n"
"       margin: 5px;\n"
"        border-radius: 10px;\n"
"    }\n"
"\n"
"    QListWidget::item:selected {\n"
"        background-color: #3498db; /* Selected item background color */\n"
"        color: #FFFFFF; /* Selected item text color */\n"
"    }\n"
"\n"
"    QListWidget::item:hover {\n"
"        background-color: #505050; /* Hovered item background color */\n"
"    }")
        self.accounts_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.accounts_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.accounts_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.accounts_table.setDragDropOverwriteMode(False)
        self.accounts_table.setAlternatingRowColors(False)
        self.accounts_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.accounts_table.setObjectName("accounts_table")
        self.gridLayout.addWidget(self.accounts_table, 0, 1, 2, 1, QtCore.Qt.AlignLeft)
        self.tabWidget.addTab(self.viewTab, "")
        self.gridLayout_5.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.main_screen)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        HomeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomeWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "MainWindow"))
        self.label_4.setText(_translate("HomeWindow", "Good Afternoon."))
        self.label_5.setText(_translate("HomeWindow", "Select a vault to login."))
        self.groupBox.setTitle(_translate("HomeWindow", "Login"))
        self.login_button.setText(_translate("HomeWindow", "Go"))
        self.delete_vault_bttn.setText(_translate("HomeWindow", "X"))
        self.label_6.setText(_translate("HomeWindow", "Create a Vault"))
        self.label_7.setText(_translate("HomeWindow", "Name"))
        self.new_name_edit.setPlaceholderText(_translate("HomeWindow", "Enter a name for this vault."))
        self.label_8.setText(_translate("HomeWindow", "Email"))
        self.new_email_edit.setPlaceholderText(_translate("HomeWindow", "Enter an email (for password reset purposes only)."))
        self.label_9.setText(_translate("HomeWindow", "Password"))
        self.new_pw_edit.setPlaceholderText(_translate("HomeWindow", "Enter a password."))
        self.back_button.setText(_translate("HomeWindow", "< Back"))
        self.create_button.setText(_translate("HomeWindow", "Create"))
        self.email_eddit.setPlaceholderText(_translate("HomeWindow", "Username/ Email"))
        self.account_name_edit.setPlaceholderText(_translate("HomeWindow", "Account Name"))
        self.acct_pw_edit.setPlaceholderText(_translate("HomeWindow", "Password"))
        self.back_to_select_bttn.setText(_translate("HomeWindow", "Back to Vaults"))
        self.add_acct_bttn.setText(_translate("HomeWindow", "Add Account"))
        self.groupBox1.setTitle(_translate("HomeWindow", "Password Options (Or type below for custom password)"))
        self.label_3.setText(_translate("HomeWindow", "Length:"))
        self.generate_pw_bttn.setText(_translate("HomeWindow", "Generate"))
        self.numbers_chkbox.setText(_translate("HomeWindow", "Numbers"))
        self.special_char_chkbox.setText(_translate("HomeWindow", "Special Characters"))
        self.uppercase_chkbox.setText(_translate("HomeWindow", "Uppercase"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.addTab), _translate("HomeWindow", "Add"))
        self.current_acct_label.setText(_translate("HomeWindow", "Website"))
        self.copy_email_bttn.setText(_translate("HomeWindow", "Copy"))
        self.copy_pw_bttn.setText(_translate("HomeWindow", "Copy"))
        self.delete_acct_bttn.setText(_translate("HomeWindow", "Delete"))
        self.edit_acct_bttn.setText(_translate("HomeWindow", "Edit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.viewTab), _translate("HomeWindow", "View"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeWindow = QtWidgets.QMainWindow()
    ui = Ui_HomeWindow()
    ui.setupUi(HomeWindow)
    HomeWindow.show()
    sys.exit(app.exec_())
